### ISSUE TITLE
more seuqencen length support?

### ISSUE THREAD

**Issue by adienxy** [seq-to-mind/DMRST_Parser#5]
I found that using xlm-roberta can only handle text sequences of limited length. I adjusted the Bert model and Bert tokenizer in MUL_main_Train.py so that the RST parsing tool supports longer texts？

**Comment by seq-to-mind** [comment]
The encoding part uses a sliding window strategy to support long text sequence. So the input length is not limited to xlm-roberta default setting.

See code here for reference:
https://github.com/seq-to-mind/DMRST_Parser/blob/231d8c0d28ba8cba074e29a6ff99e858e4742735/module.py#L58-L75

**Comment by adienxy** [comment]
> The encoding part uses a sliding window strategy to support long text sequence. So the input length is not limited to xlm-roberta default setting.
> 
> See code here for reference:
> 
> https://github.com/seq-to-mind/DMRST_Parser/blob/231d8c0d28ba8cba074e29a6ff99e858e4742735/module.py#L58-L75

Thank you for your reply; I am honored that you responded so quickly!
The reason why I ask this question is that I noticed that when running MUL_main_Infer.py to infer a sentence, the following prompt appeared: 
_**Token indices sequence length is longer than the specified maximum sequence length for this model (1146 > 512). Running this sequence through the model will result in indexing errors**_
Does this mean that I need to re-run MUL_main_Train.py for training after replacing the tokenizer and model to obtain the .torchsave file to accommodate longer text sequences?

**Comment by seq-to-mind** [comment]
I guess this warning message comes from this line, you can check it in running log.
https://github.com/seq-to-mind/DMRST_Parser/blob/231d8c0d28ba8cba074e29a6ff99e858e4742735/MUL_main_Infer.py#L27

This is because the tokenizer found the input is longer than the default setting of xlm-roberta and pop the warning message. This is a feature added in newer Transformers library. In fact, the tokenized long sequence will be processed by the sliding window encoding, so this warning can be ignored.

If you cannot get the parsing output, attach the complete log.

**Comment by seq-to-mind** [comment]
The parser indeed supporting long text sequence input, there is no need to retrain for that.

**Comment by adienxy** [comment]
> The parser indeed supporting long text sequence input, there is no need to retrain for that.

You have answered my question. I sincerely thank you for your answer. I wish you success in your work and good health!
